Repository hazelcast/hazelcast-cpp-client, pull requests merged in 2018-10, with the labels that each got.

#454 Implement the create proxy request for map proxy
  hazelcast/generated-sources/include/hazelcast/client/protocol/codec/ClientCreateProxyCodec.h
  hazelcast/generated-sources/src/hazelcast/client/protocol/codec/ClientCreateProxyCodec.cpp
  hazelcast/include/hazelcast/client/DistributedObject.h
  hazelcast/include/hazelcast/client/IDistributedObject.h
  hazelcast/include/hazelcast/client/IList.h
  hazelcast/include/hazelcast/client/IQueue.h
  hazelcast/include/hazelcast/client/ISet.h
  hazelcast/include/hazelcast/client/ITopic.h
  hazelcast/include/hazelcast/client/MultiMap.h
  hazelcast/include/hazelcast/client/ReliableTopic.h
  hazelcast/include/hazelcast/client/Ringbuffer.h
  hazelcast/include/hazelcast/client/adaptor/RawPointerList.h
  hazelcast/include/hazelcast/client/adaptor/RawPointerMultiMap.h
  hazelcast/include/hazelcast/client/adaptor/RawPointerQueue.h
  hazelcast/include/hazelcast/client/adaptor/RawPointerSet.h
  hazelcast/include/hazelcast/client/crdt/pncounter/PNCounter.h
  hazelcast/include/hazelcast/client/exception/ProtocolExceptions.h
  hazelcast/include/hazelcast/client/impl/HazelcastClientInstanceImpl.h
  hazelcast/include/hazelcast/client/map/ClientMapProxy.h
  hazelcast/include/hazelcast/client/map/NearCachedClientMapProxy.h
  hazelcast/include/hazelcast/client/mixedtype/ClientMapProxy.h
  hazelcast/include/hazelcast/client/mixedtype/IList.h
  hazelcast/include/hazelcast/client/mixedtype/MultiMap.h
  hazelcast/include/hazelcast/client/proxy/ProxyImpl.h
  hazelcast/include/hazelcast/client/proxy/RingbufferImpl.h
  hazelcast/include/hazelcast/client/spi/ClientClusterService.h
  hazelcast/include/hazelcast/client/spi/ClientContext.h
  hazelcast/include/hazelcast/client/spi/ClientProxy.h
  hazelcast/include/hazelcast/client/spi/ProxyManager.h
  hazelcast/include/hazelcast/client/spi/impl/ClientClusterServiceImpl.h
  hazelcast/include/hazelcast/client/spi/impl/ClientInvocation.h
  hazelcast/src/hazelcast/client/DistributedObject.cpp
  hazelcast/src/hazelcast/client/ILock.cpp
  hazelcast/src/hazelcast/client/exception/ProtocolExceptions.cpp
  hazelcast/src/hazelcast/client/impl/HazelcastClientInstanceImpl.cpp
  hazelcast/src/hazelcast/client/mixedtype/ClientMapProxy.cpp
  hazelcast/src/hazelcast/client/mixedtype/IList.cpp
  hazelcast/src/hazelcast/client/mixedtype/IQueue.cpp
  hazelcast/src/hazelcast/client/mixedtype/ISet.cpp
  hazelcast/src/hazelcast/client/mixedtype/ITopic.cpp
  hazelcast/src/hazelcast/client/mixedtype/MultiMap.cpp
  hazelcast/src/hazelcast/client/mixedtype/NearCachedClientMapProxy.cpp
  hazelcast/src/hazelcast/client/mixedtype/Ringbuffer.cpp
  hazelcast/src/hazelcast/client/proxy/IListImpl.cpp
  hazelcast/src/hazelcast/client/proxy/IMapImpl.cpp
  hazelcast/src/hazelcast/client/proxy/IQueueImpl.cpp
  hazelcast/src/hazelcast/client/proxy/ISetImpl.cpp
  hazelcast/src/hazelcast/client/proxy/MultiMapImpl.cpp
  hazelcast/src/hazelcast/client/proxy/ProxyImpl.cpp
  hazelcast/src/hazelcast/client/proxy/TopicImpl.cpp
  hazelcast/src/hazelcast/client/spi/ClientContext.cpp
  hazelcast/src/hazelcast/client/spi/ClientProxy.cpp
  hazelcast/src/hazelcast/client/spi/ProxyManager.cpp
  hazelcast/src/hazelcast/client/spi/impl/ClientClusterServiceImpl.cpp
  hazelcast/src/hazelcast/client/spi/impl/ProxyManager.cpp
  hazelcast/src/hazelcast/util/concurrent/CancellationException.cpp
  hazelcast/test/src/connectionstrategy/ConfiguredBehaviourTest.cpp
  scripts/start-rc.sh
Labels: Estimation: S

#456 Thread termination passed argument memory leak fix
  hazelcast/include/hazelcast/util/PosixThread.inl
  hazelcast/include/hazelcast/util/WindowsThread.inl
  hazelcast/src/hazelcast/client/connection/ClientConnectionManagerImpl.cpp
Labels: Estimation: S, Type: Defect

#459 Release build verification fails with missing header dependencies "boost/noncopyable.hpp and easylogging++/easylogging++.h: No such file or directory"
  external/release_include/boost/core/noncopyable.hpp
  external/release_include/boost/noncopyable.hpp
  external/release_include/easylogging++/easylogging++.h
Labels: Type: Enhancement, Type: Test-Failure

#460 LoggerConfigFromFileTest.testFinest may fail at Windows builds
  hazelcast/test/src/util/LoggerConfigFromFileTest.cpp
Labels: Type: Test-Failure

#461 Easylogging++ does not detect C++11 compiler enabled/disabled correctly
  external/include/easylogging++/easylogging++.h
  external/release_include/easylogging++/easylogging++.h
Labels: Type: Test-Failure

#462 Enable easylogger debug output when build type is "Release"
  external/include/easylogging++/easylogging++.h
  external/release_include/easylogging++/easylogging++.h
  hazelcast/test/resources/logger-config.txt
  hazelcast/test/src/ClientTestSupport.h
  hazelcast/test/src/util/ClientUtilTest.cpp
  hazelcast/test/src/util/LoggerConfigFromFileTest.cpp
Labels: Type: Test-Failure

#463 Adding missing virtual destructors to abstract base classes
  hazelcast/include/hazelcast/client/cluster/memberselector/MemberSelectors.h
  hazelcast/include/hazelcast/client/connection/AddressProvider.h
  hazelcast/include/hazelcast/client/flakeidgen/impl/AutoBatcher.h
  hazelcast/include/hazelcast/client/impl/Partition.h
  hazelcast/include/hazelcast/client/spi/EventHandler.h
Labels: Type: Defect
