Repository hazelcast/hazelcast-cpp-client, pull requests merged in 2018-08, with the labels that each got.

#442 Change PNCounter to "PN Counter" in the README doc
  README.md
  hazelcast/test/src/adaptor/RawPointerTxnMultiMapTest.cpp
Labels: Estimation: L, Priority: Low, Type: Documentation

#444 README is need for the examples
  examples/CMakeLists.txt
  examples/README.md
  examples/command-line-tool/CMakeLists.txt
  examples/command-line-tool/CommandLineTool.cpp
Labels: Estimation: S, Priority: Low, Type: Documentation

#445 Wait the thread to actually finish before the Thread destructor exits
  hazelcast/include/hazelcast/client/connection/ClientConnectionManagerImpl.h
  hazelcast/include/hazelcast/client/impl/HazelcastClientInstanceImpl.h
  hazelcast/include/hazelcast/client/spi/ClientContext.h
  hazelcast/include/hazelcast/util/PosixThread.inl
  hazelcast/include/hazelcast/util/WindowsThread.inl
  hazelcast/include/hazelcast/util/impl/AbstractThread.h
  hazelcast/src/hazelcast/client/connection/ClientConnectionManagerImpl.cpp
  hazelcast/src/hazelcast/client/spi/ClientContext.cpp
  hazelcast/src/hazelcast/util/impl/AbstractThread.cpp
Labels: Estimation: S, Priority: Medium, Type: Defect

#447 Release build fails since release includes misses enable_shared_from_this.hpp
  external/release_include/boost/enable_shared_from_this.hpp
  external/release_include/boost/smart_ptr/enable_shared_from_this.hpp
  external/release_include/boost/smart_ptr/weak_ptr.hpp
Labels: Estimation: S

#448 PN counter section link is not working
  README.md
Labels: Estimation: S, Priority: Low, Type: Documentation

#453 releaseOSX.sh fails to copy 32 bit library binaries
  releaseOSX.sh
Labels: Estimation: S, Priority: Low, Type: Defect

#452 Memory leak in ASan report
  hazelcast/include/hazelcast/client/spi/impl/sequence/CallIdSequence.h
  hazelcast/include/hazelcast/util/concurrent/IdleStrategy.h
Labels: Estimation: S, Priority: Medium, Type: Defect
