Repository hazelcast/hazelcast-cpp-client, pull requests merged in 2019-02, with the labels that each got.

#514 Add the gcc -pipe option to avoid build error related to /tmp file system
  CMakeLists.txt
Labels: Type: Enhancement, Type: Test-Failure

#517 Remove the SyncronizedMap usage from VectorClock
  hazelcast/include/hazelcast/client/cluster/impl/VectorClock.h
  hazelcast/src/hazelcast/client/cluster/impl/VectorClock.cpp
  hazelcast/src/hazelcast/client/proxy/ClientPNCounterProxy.cpp
Labels: Estimation: S, Type: Enhancement

#520 Remove recently introduced boost/date_time dependency from the released includes
  hazelcast/include/hazelcast/client/map/ClientMapProxy.h
  hazelcast/include/hazelcast/client/proxy/IMapImpl.h
  hazelcast/include/hazelcast/util/TimeUtil.h
  hazelcast/src/hazelcast/client/proxy/IMapImpl.cpp
  hazelcast/src/hazelcast/util/TimeUtil.cpp
Labels: Estimation: S, Priority: Medium, Type: Test-Failure

#521 Make release builds complete faster
  releaseLinux.sh
  releaseOSX.sh
  scripts/build-linux.sh
  scripts/verifyReleaseLinux.sh
  scripts/verifyReleaseLinuxSingleCase.sh
  scripts/verifyReleaseOSX.sh
Labels: Type: Enhancement

#513 Async API implementation for the NearCachedClientMapProxy
  hazelcast/include/hazelcast/client/map/ClientMapProxy.h
  hazelcast/include/hazelcast/client/map/NearCachedClientMapProxy.h
  hazelcast/include/hazelcast/client/map/impl/ClientMapProxyFactory.h
  hazelcast/include/hazelcast/client/mixedtype/NearCachedClientMapProxy.h
  hazelcast/include/hazelcast/client/proxy/ProxyImpl.h
  hazelcast/include/hazelcast/client/spi/ClientProxy.h
  hazelcast/include/hazelcast/client/spi/ProxyManager.h
  hazelcast/include/hazelcast/util/SynchronizedMap.h
  hazelcast/src/hazelcast/client/mixedtype/NearCachedClientMapProxy.cpp
  hazelcast/src/hazelcast/client/spi/ClientProxy.cpp
  hazelcast/src/hazelcast/client/spi/LifecycleService.cpp
  hazelcast/src/hazelcast/client/spi/ProxyManager.cpp
Labels: Estimation: S, Type: Enhancement

#523 Add missing exception codes, make TopologyChangedException non-retryable
  hazelcast/include/hazelcast/client/exception/ProtocolExceptions.h
  hazelcast/include/hazelcast/client/protocol/ClientProtocolErrorCodes.h
Labels: Estimation: S, Type: Defect, Type: Enhancement

#519 Solved what is conflict with mysql-dev
  hazelcast/include/hazelcast/client/protocol/ClientMessage.h
  hazelcast/include/hazelcast/client/spi/impl/AbstractInvocationFuture.h
  hazelcast/src/hazelcast/client/protocol/ClientMessage.cpp
Labels: Type: Enhancement

#525 Implement the missing async API for Ringbuffer
  hazelcast/generated-sources/include/hazelcast/client/protocol/codec/RingbufferAddAllCodec.h
  hazelcast/generated-sources/src/hazelcast/client/protocol/codec/RingbufferAddAllCodec.cpp
  hazelcast/include/hazelcast/client/Ringbuffer.h
  hazelcast/include/hazelcast/client/impl/HazelcastClientInstanceImpl.h
  hazelcast/include/hazelcast/client/proxy/ClientRingbufferProxy.h
  hazelcast/include/hazelcast/client/proxy/PartitionSpecificClientProxy.h
  hazelcast/include/hazelcast/client/proxy/RingbufferImpl.h
  hazelcast/include/hazelcast/client/ringbuffer/ReadResultSet.h
  hazelcast/include/hazelcast/client/ringbuffer/impl/RingbufferProxyFactory.h
  hazelcast/include/hazelcast/client/spi/ClientProxy.h
  hazelcast/include/hazelcast/util/Preconditions.h
  hazelcast/src/hazelcast/client/mixedtype/Ringbuffer.cpp
  hazelcast/src/hazelcast/client/topic/impl/reliable/ReliableTopicExecutor.cpp
  hazelcast/test/resources/hazelcast.xml
  hazelcast/test/src/ClientTestSupport.cpp
  hazelcast/test/src/TestHelperFunctions.h
  hazelcast/test/src/executor/tasks/IdentifiedFactory.h
  hazelcast/test/src/ringbuffer/MixedRingbufferTest.cpp
  hazelcast/test/src/ringbuffer/RingBufferTest.cpp
  hazelcast/test/src/ringbuffer/StartsWithStringFilter.cpp
  hazelcast/test/src/ringbuffer/StartsWithStringFilter.h
Labels: Estimation: S, Type: Enhancement

#531 IAtomicLong async API usage example
  examples/distributed-primitives/atomiclong/AtomicLongAsyncApi.cpp
  examples/distributed-primitives/atomiclong/CMakeLists.txt
Labels: Type: Enhancement

#532 Ringbuffer async API usage example
  examples/distributed-collections/ringbuffer/CMakeLists.txt
  examples/distributed-collections/ringbuffer/RingbufferAsyncApi.cpp
  hazelcast/include/hazelcast/client/Ringbuffer.h
Labels: Type: Enhancement

#535 Explain better what is returned from Message.getPublishTime
  hazelcast/include/hazelcast/client/topic/Message.h
Labels: Type: Documentation

#534 Add the documentation for the Asynchronous API usages
  README.md
Labels: Type: Documentation
