Repository hazelcast/hazelcast-cpp-client, pull requests merged in 2020-09, with the labels that each got.

#621 Cleanup of deprecated classes
  examples/distributed-map/near-cache/NearCacheWithMaxIdle.cpp
  examples/distributed-map/near-cache/NearCacheWithMemoryFormatBinary.cpp
  examples/distributed-map/near-cache/NearCacheWithMemoryFormatObject.cpp
  examples/distributed-map/near-cache/NearCacheWithTTL.cpp
  examples/network-configuration/shuffle-memberlist/ShuffleMemberList.cpp
  examples/network-configuration/tcpip/main.cpp
  examples/soak-test/SoakTest.cpp
  examples/tls/BasicTLSClient.cpp
  hazelcast/include/hazelcast/client/ClientConfig.h
  hazelcast/include/hazelcast/client/connection/Connection.h
  hazelcast/include/hazelcast/client/impl/BuildInfo.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/src/hazelcast/client/stats.cpp
  hazelcast/test/src/HazelcastTests1.cpp
  hazelcast/test/src/HazelcastTests2.cpp
  hazelcast/test/src/HazelcastTests5.cpp
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Enhancement

#614 Change LifecycleListener
  examples/network-configuration/connection-strategy/DoNotReconnectToCluster.cpp
  examples/network-configuration/connection-strategy/ReconnectAsync.cpp
  examples/network-configuration/connection-strategy/StartAsync.cpp
  hazelcast/include/hazelcast/client/ClientConfig.h
  hazelcast/include/hazelcast/client/HazelcastClient.h
  hazelcast/include/hazelcast/client/LifecycleEvent.h
  hazelcast/include/hazelcast/client/LifecycleListener.h
  hazelcast/include/hazelcast/client/impl/HazelcastClientInstanceImpl.h
  hazelcast/include/hazelcast/client/spi/LifecycleService.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/test/src/HazelcastTests1.cpp
  hazelcast/test/src/HazelcastTests2.cpp
Labels: Type: Enhancement

#619 Fix 32 bit linux and all release builds
  hazelcast/test/src/serialization/Serializables.cpp
  scripts/build-linux.sh
Labels: Type: Defect

#622 CP atomic_long, atomic_reference, and latch implementations
  CMakeLists.txt
  hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.cpp
  hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.h
  hazelcast/include/hazelcast/client/HazelcastClient.h
  hazelcast/include/hazelcast/client/impl/HazelcastClientInstanceImpl.h
  hazelcast/include/hazelcast/client/protocol/ClientMessage.h
  hazelcast/include/hazelcast/cp/cp.h
  hazelcast/include/hazelcast/cp/cp_impl.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/protocol.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/src/hazelcast/cp/cp.cpp
  hazelcast/src/hazelcast/cp/cp_impl.cpp
  hazelcast/test/src/IdentifiedSerializables.h
  hazelcast/test/src/TestHelperFunctions.h
  hazelcast/test/src/cp_test.cpp
  scripts/start-rc.bat
  scripts/start-rc.sh
Labels: Type: Enhancement

#629 Fix basic_latch_test.test_try_set_count_when_count_is_not_zero
  hazelcast/test/src/cp_test.cpp
Labels: Type: Cleanup, Type: Test-Failure

#627 Fenced lock implementation
  hazelcast/include/hazelcast/client/exception/ProtocolExceptions.h
  hazelcast/include/hazelcast/client/impl/HazelcastClientInstanceImpl.h
  hazelcast/include/hazelcast/client/proxy/SerializingProxy.h
  hazelcast/include/hazelcast/client/spi/ClientContext.h
  hazelcast/include/hazelcast/cp/cp.h
  hazelcast/include/hazelcast/cp/cp_impl.h
  hazelcast/include/hazelcast/util/SynchronizedMap.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/protocol.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/src/hazelcast/cp/cp.cpp
  hazelcast/src/hazelcast/cp/cp_impl.cpp
  hazelcast/test/src/HazelcastServerFactory.h
  hazelcast/test/src/HazelcastTests5.cpp
  hazelcast/test/src/cp_test.cpp
Labels: Type: Enhancement

#633 Backport of https://github.com/hazelcast/hazelcast/pull/17578 -
  hazelcast/src/hazelcast/client/network.cpp
Labels: Type: Enhancement

#626 Change MembershipListener, Remove InitialMembershipListener
  examples/monitoring/cluster/main.cpp
  hazelcast/include/hazelcast/client/ClientConfig.h
  hazelcast/include/hazelcast/client/Cluster.h
  hazelcast/include/hazelcast/client/HazelcastAll.h
  hazelcast/include/hazelcast/client/InitialMembershipEvent.h
  hazelcast/include/hazelcast/client/InitialMembershipListener.h
  hazelcast/include/hazelcast/client/MembershipEvent.h
  hazelcast/include/hazelcast/client/MembershipListener.h
  hazelcast/include/hazelcast/client/impl/AbstractLoadBalancer.h
  hazelcast/include/hazelcast/client/spi/impl/ClientClusterServiceImpl.h
  hazelcast/src/hazelcast/client/cluster.cpp
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/test/src/HazelcastTests1.cpp
  hazelcast/test/src/HazelcastTests3.cpp
  hazelcast/test/src/HazelcastTests7.cpp
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Enhancement

#628 Change ReliableMessageListener
  examples/distributed-topic/basic-pub-sub/Subscriber.cpp
  examples/distributed-topic/reliabletopic/Subscriber.cpp
  hazelcast/include/hazelcast/client/ReliableTopic.h
  hazelcast/include/hazelcast/client/proxy/ReliableTopicImpl.h
  hazelcast/include/hazelcast/client/topic/Listener.h
  hazelcast/include/hazelcast/client/topic/ReliableListener.h
  hazelcast/include/hazelcast/client/topic/ReliableMessageListener.h
  hazelcast/include/hazelcast/client/topic/impl/TopicEventHandlerImpl.h
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Enhancement

#630 Change SocketInterceptor
  examples/network-configuration/socket-interceptor/main.cpp
  hazelcast/include/hazelcast/client/ClientConfig.h
  hazelcast/include/hazelcast/client/SocketInterceptor.h
  hazelcast/include/hazelcast/client/connection/ClientConnectionManagerImpl.h
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/test/src/HazelcastTests1.cpp
Labels: Type: Enhancement
