Repository hazelcast/hazelcast-cpp-client, pull requests merged in 2020-11, with the labels that each got.

#672 Find and link to the correct Boost, thrift and openssl versions at Windows using the vcpkg toolchain
  CMakeLists.txt
  README.md
  hazelcast/test/src/CMakeLists.txt
  scripts/build-windows.bat
  testWindowsSingleCase.bat
Labels: Type: Test-Failure

#669 Enable ClientStatisticsTest
  hazelcast/include/hazelcast/client/connection/Connection.h
  hazelcast/include/hazelcast/client/spi/impl/ClientExecutionServiceImpl.h
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/src/hazelcast/client/stats.cpp
  hazelcast/src/hazelcast/util/util.cpp
  hazelcast/test/src/HazelcastTests1.cpp
Labels: Type: Enhancement

#670 Cleanup: Removed the commented out test which not really needed
  hazelcast/test/src/HazelcastTests5.cpp
Labels: Type: Cleanup

#677 API change: Remove template usage in NearCacheConfig and EvictionConfig
  README.md
  examples/client-statistics/ClientStatistics.cpp
  examples/distributed-map/near-cache/NearCacheWithEvictionPolicy.cpp
  examples/distributed-map/near-cache/NearCacheWithInvalidation.cpp
  examples/distributed-map/near-cache/NearCacheWithMaxIdle.cpp
  examples/distributed-map/near-cache/NearCacheWithMemoryFormatBinary.cpp
  examples/distributed-map/near-cache/NearCacheWithMemoryFormatObject.cpp
  examples/distributed-map/near-cache/NearCacheWithTTL.cpp
  hazelcast/include/hazelcast/client/ClientConfig.h
  hazelcast/include/hazelcast/client/config/EvictionConfig.h
  hazelcast/include/hazelcast/client/config/NearCacheConfig.h
  hazelcast/include/hazelcast/client/config/NearCacheConfigBase.h
  hazelcast/include/hazelcast/client/internal/config/ConfigUtils.h
  hazelcast/include/hazelcast/client/internal/eviction/EvictionPolicyEvaluatorProvider.h
  hazelcast/include/hazelcast/client/internal/eviction/EvictionStrategyProvider.h
  hazelcast/include/hazelcast/client/internal/nearcache/NearCacheManager.h
  hazelcast/include/hazelcast/client/internal/nearcache/impl/DefaultNearCache.h
  hazelcast/include/hazelcast/client/internal/nearcache/impl/store/AbstractNearCacheRecordStore.h
  hazelcast/include/hazelcast/client/internal/nearcache/impl/store/BaseHeapNearCacheRecordStore.h
  hazelcast/include/hazelcast/client/internal/nearcache/impl/store/NearCacheDataRecordStore.h
  hazelcast/include/hazelcast/client/internal/nearcache/impl/store/NearCacheObjectRecordStore.h
  hazelcast/include/hazelcast/client/map/NearCachedClientMapProxy.h
  hazelcast/include/hazelcast/client/proxy/ReplicatedMapImpl.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/test/src/HazelcastTests1.cpp
  hazelcast/test/src/HazelcastTests2.cpp
  hazelcast/test/src/HazelcastTests3.cpp
  hazelcast/test/src/HazelcastTests5.cpp
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Enhancement

#674 Use std::chrono::duration for timeout values of network configurations
  hazelcast/include/hazelcast/client/IMap.h
  hazelcast/include/hazelcast/client/IQueue.h
  hazelcast/include/hazelcast/client/MultiMap.h
  hazelcast/include/hazelcast/client/ReplicatedMap.h
  hazelcast/include/hazelcast/client/TransactionOptions.h
  hazelcast/include/hazelcast/client/TransactionalQueue.h
  hazelcast/include/hazelcast/client/config/ClientFlakeIdGeneratorConfig.h
  hazelcast/include/hazelcast/client/config/ClientNetworkConfig.h
  hazelcast/include/hazelcast/client/connection/ClientConnectionManagerImpl.h
  hazelcast/include/hazelcast/client/connection/Connection.h
  hazelcast/include/hazelcast/client/connection/HeartbeatManager.h
  hazelcast/include/hazelcast/client/connection/ReadHandler.h
  hazelcast/include/hazelcast/client/internal/socket/BaseSocket.h
  hazelcast/include/hazelcast/client/internal/socket/SSLSocket.h
  hazelcast/include/hazelcast/client/internal/socket/SocketFactory.h
  hazelcast/include/hazelcast/client/internal/socket/TcpSocket.h
  hazelcast/include/hazelcast/client/map/NearCachedClientMapProxy.h
  hazelcast/include/hazelcast/client/proxy/FlakeIdGeneratorImpl.h
  hazelcast/include/hazelcast/client/proxy/IMapImpl.h
  hazelcast/include/hazelcast/client/proxy/IQueueImpl.h
  hazelcast/include/hazelcast/client/proxy/MultiMapImpl.h
  hazelcast/include/hazelcast/client/proxy/ReplicatedMapImpl.h
  hazelcast/include/hazelcast/client/proxy/TransactionalObject.h
  hazelcast/include/hazelcast/client/proxy/TransactionalQueueImpl.h
  hazelcast/include/hazelcast/client/spi/impl/ClientClusterServiceImpl.h
  hazelcast/include/hazelcast/client/spi/impl/ClientExecutionServiceImpl.h
  hazelcast/include/hazelcast/client/spi/impl/ClientInvocation.h
  hazelcast/include/hazelcast/client/spi/impl/ClientInvocationServiceImpl.h
  hazelcast/include/hazelcast/client/spi/impl/ClientTransactionManagerServiceImpl.h
  hazelcast/include/hazelcast/client/spi/impl/listener/listener_service_impl.h
  hazelcast/include/hazelcast/client/txn/TransactionProxy.h
  hazelcast/include/hazelcast/cp/cp.h
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/src/hazelcast/client/proxy.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/src/hazelcast/client/transactions.cpp
  hazelcast/src/hazelcast/cp/cp.cpp
  hazelcast/test/src/HazelcastTests1.cpp
  hazelcast/test/src/HazelcastTests2.cpp
  hazelcast/test/src/HazelcastTests8.cpp
  hazelcast/test/src/cp_test.cpp
Labels: Type: Enhancement

#678 [BACKPORT from Java doc] Fixes the documentation of semaphore release method
  hazelcast/include/hazelcast/cp/cp.h
Labels: Type: Documentation

#683 Change test server version to 4.1
  scripts/start-rc.bat
  scripts/start-rc.sh
Labels: Type: Enhancement

#684 Wait for session close invocation results during session manager close
  hazelcast/include/hazelcast/cp/cp_impl.h
  hazelcast/src/hazelcast/cp/cp_impl.cpp
Labels: Type: Test-Failure

#685 Make client_config move-only, Use unique_ptr for load_balancer
  examples/Org.Website.Samples/GlobalSerializerSample.cpp
  examples/authentication/token_authentication.cpp
  examples/authentication/username_password_authentication.cpp
  examples/aws/AwsClientWithKey.cpp
  examples/aws/AwsClientWithNoKeyNoIAMRoleInsideAws.cpp
  examples/aws/AwsClientWithNoKeyWithIAMRoleInsideAws.cpp
  examples/backpressure/EnableBackPressure.cpp
  examples/client-statistics/ClientStatistics.cpp
  examples/distributed-map/near-cache/NearCacheWithEvictionPolicy.cpp
  examples/distributed-map/near-cache/NearCacheWithInvalidation.cpp
  examples/distributed-map/near-cache/NearCacheWithMaxIdle.cpp
  examples/distributed-map/near-cache/NearCacheWithMemoryFormatBinary.cpp
  examples/distributed-map/near-cache/NearCacheWithMemoryFormatObject.cpp
  examples/distributed-map/near-cache/NearCacheWithTTL.cpp
  examples/distributed-topic/reliabletopic/Publisher.cpp
  examples/distributed-topic/reliabletopic/Subscriber.cpp
  examples/event-properties/SetEventThreadCountAndMaxQueueSize.cpp
  examples/invocation-timeouts/SetInvocationTimeouts.cpp
  examples/learning-basics/configure-logging/custom_log_handler.cpp
  examples/learning-basics/configure-logging/disable_logging.cpp
  examples/learning-basics/configure-logging/set_level.cpp
  examples/network-configuration/backup-ack/disable_backup_ack.cpp
  examples/network-configuration/connection-strategy/DoNotReconnectToCluster.cpp
  examples/network-configuration/connection-strategy/ReconnectAsync.cpp
  examples/network-configuration/connection-strategy/StartAsync.cpp
  examples/network-configuration/shuffle-memberlist/ShuffleMemberList.cpp
  examples/network-configuration/socket-interceptor/main.cpp
  examples/network-configuration/tcpip/main.cpp
  examples/pipeline/PipeliningDemo.cpp
  examples/serialization/globalserializer/main.cpp
  examples/tls/BasicTLSClient.cpp
  hazelcast/include/hazelcast/client/client_config.h
  hazelcast/include/hazelcast/client/connection/ClientConnectionManagerImpl.h
  hazelcast/include/hazelcast/client/hazelcast_client.h
  hazelcast/include/hazelcast/client/impl/hazelcast_client_instance_impl.h
  hazelcast/include/hazelcast/client/serialization/pimpl/data_output.h
  hazelcast/include/hazelcast/client/spi/lifecycle_service.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/test/src/HazelcastTests1.cpp
  hazelcast/test/src/HazelcastTests2.cpp
  hazelcast/test/src/HazelcastTests3.cpp
  hazelcast/test/src/HazelcastTests5.cpp
  hazelcast/test/src/HazelcastTests7.cpp
  hazelcast/test/src/HazelcastTests8.cpp
  hazelcast/test/src/cp_test.cpp
Labels: Type: Enhancement

#681 Fix Windows, Mac OS and Linux release scripts
  examples/CMakeLists.txt
  hazelcast/include/hazelcast/client/hazelcast_client.h
  hazelcast/include/hazelcast/client/spi/impl/ClientExecutionServiceImpl.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  releaseLinux.sh
  releaseOSX.sh
  releaseWindows.bat
  scripts/build-linux.sh
  scripts/build_linux_release_libraries.sh
  scripts/verifyReleaseLinux.sh
  scripts/verifyReleaseLinuxSingleCase.sh
  scripts/verifyReleaseOSX.sh
  scripts/verifyReleaseWindows.bat
  scripts/verifyReleaseWindowsSingleCase.bat
Labels: Type: Test-Failure

#691 Update soak_test to work with 4.0 release changes
  examples/soak-test/CMakeLists.txt
  examples/soak-test/README.md
  examples/soak-test/SoakTest.cpp
  examples/soak-test/soak_test.cpp
Labels: Type: Enhancement

#688 Logger enhancements
  hazelcast/include/hazelcast/logger.h
  hazelcast/src/hazelcast/logger.cpp
  hazelcast/test/src/HazelcastTests2.cpp
Labels: Type: Enhancement

#693 soak_test thread safe random usage and client_config move fixes
  examples/soak-test/CMakeLists.txt
  examples/soak-test/soak_test.cpp
Labels: Type: Enhancement

#694 soak_test fails to progress when the second client is started due to client uuid conflicts
  examples/CMakeLists.txt
  examples/soak-test/CMakeLists.txt
  examples/soak-test/soak_test.cpp
  hazelcast/include/hazelcast/logger.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/protocol.cpp
  hazelcast/src/hazelcast/client/spi.cpp
Labels: Type: Test-Failure

#695 soak-test build fails for the release verification build - cmake file extra parameters are not needed
  examples/soak-test/CMakeLists.txt
Labels: Type: Test-Failure

#697 use std::random for uuid generator seed value
  hazelcast/src/hazelcast/client/client_impl.cpp
Labels: Type: Enhancement

#698 Windows release build failure (due to the linux only posix `sigaction` api usage) fix
  examples/soak-test/soak_test.cpp
Labels: Type: Test-Failure

#700 `ClientConfig::set_instance_name` API should work with simple std::string
  examples/soak-test/soak_test.cpp
  hazelcast/include/hazelcast/client/client_config.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/test/src/HazelcastTests2.cpp
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Cleanup, api-change

#701 Eliminate the extra include and examples folders under the platform specific folders in release zip
  README.md
  examples/CMakeLists.txt
  hazelcast/src/hazelcast/client/client_impl.cpp
  releaseLinux.sh
  releaseOSX.sh
  releaseWindows.bat
  scripts/build-windows.bat
  scripts/build_linux_release_libraries.sh
  scripts/verifyReleaseWindowsSingleCase.bat
Labels: Type: Enhancement

#704 Fix to `releaseOSX.sh`
  README.md
  releaseOSX.sh
Labels: Type: Enhancement

#705 Make the project compile at gcc 4.8.5
  README.md
  hazelcast/include/hazelcast/client/entry_listener.h
  hazelcast/include/hazelcast/client/imap.h
  hazelcast/include/hazelcast/client/impl/statistics/Statistics.h
  hazelcast/include/hazelcast/client/item_listener.h
  hazelcast/include/hazelcast/client/lifecycle_listener.h
  hazelcast/include/hazelcast/client/membership_listener.h
  hazelcast/include/hazelcast/client/protocol/ClientMessage.h
  hazelcast/include/hazelcast/client/proxy/SerializingProxy.h
  hazelcast/include/hazelcast/client/reliable_topic.h
  hazelcast/include/hazelcast/cp/cp_impl.h
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/src/hazelcast/client/stats.cpp
  hazelcast/src/hazelcast/logger.cpp
  hazelcast/src/hazelcast/util/util.cpp
  hazelcast/test/src/HazelcastTests2.cpp
Labels: Type: Enhancement

#706 `std::rethrow_if_nested(std::current_exception()) does not work in gcc 4.8
  README.md
  hazelcast/include/hazelcast/client/reliable_topic.h
  hazelcast/src/hazelcast/util/util.cpp
Labels: Type: Enhancement

#708 Support release binary built in gcc 5.3
  docker/hazelcast-fedora-i386.dockerfile
  docker/hazelcast-fedora22-x86_64.dockerfile
  releaseLinux.sh
  scripts/build-linux.sh
  scripts/build_linux_release_libraries.sh
Labels: Type: Enhancement

#712 Script fix for failure to generate the windows 64-bit TLS library
  releaseWindows.bat
  scripts/verifyReleaseWindowsSingleCase.bat
Labels: Type: Enhancement

#713 Fix documentation config
  Doxyfile
  releaseOSX.sh
Labels: Type: Documentation

#710 Mac OSX release verification script failure fix
  CMakeLists.txt
  examples/CMakeLists.txt
Labels: Type: Enhancement
