Repository hazelcast/hazelcast-cpp-client, pull requests merged in 2021-04, with the labels that each got.

#840 Fix -Wunused-private-field
  hazelcast/include/hazelcast/client/aws/aws_client.h
  hazelcast/include/hazelcast/client/spi/impl/discovery/cloud_discovery.h
  hazelcast/src/hazelcast/client/discovery.cpp
  hazelcast/src/hazelcast/client/spi.cpp
Labels: Type: Enhancement

#841 Replace ssl::host_name_verification with ssl::rfc2818_verification
  hazelcast/src/hazelcast/util/util.cpp
Labels: Type: Defect

#843 Add a new section to redirect users to use Hazelcast Command Line tools
  Reference_Manual.md
Labels: Type: Documentation

#846 Fix the uninitialised memory usage warning during valgrind analysis
  hazelcast/include/hazelcast/client/internal/socket/BaseSocket.h
Labels: Type: Enhancement

#850 Break cyclic shared_ptr usages between ClientInvocation, Connection and cluster_view_listener::event_listener
  hazelcast/include/hazelcast/client/iexecutor_service.h
  hazelcast/include/hazelcast/client/spi/impl/ClientInvocation.h
  hazelcast/include/hazelcast/client/spi/impl/ClientPartitionServiceImpl.h
  hazelcast/include/hazelcast/client/spi/impl/listener/cluster_view_listener.h
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/src/hazelcast/client/spi.cpp
Labels: Type: Defect

#855 Update the test server version to 4.1.4-SNAPSHOT
  scripts/start-rc.bat
  scripts/start-rc.sh
Labels: Type: Test-Failure

#853 Remove redundant static/shared library logic in CMakeLists.txt
  CMakeLists.txt
Labels: Type: Enhancement

#849 `client_config::reliable_topic_config_map_` should not be modified concurrently
  examples/distributed-topic/reliabletopic/Publisher.cpp
  examples/distributed-topic/reliabletopic/Subscriber.cpp
  hazelcast/include/hazelcast/client/client_config.h
  hazelcast/include/hazelcast/client/config/reliable_topic_config.h
  hazelcast/include/hazelcast/client/hazelcast_client.h
  hazelcast/include/hazelcast/client/proxy/ReliableTopicImpl.h
  hazelcast/include/hazelcast/client/proxy/RingbufferImpl.h
  hazelcast/include/hazelcast/client/reliable_topic.h
  hazelcast/include/hazelcast/client/ringbuffer.h
  hazelcast/include/hazelcast/client/topic/impl/reliable/ReliableTopicExecutor.h
  hazelcast/include/hazelcast/util/BlockingConcurrentQueue.h
  hazelcast/include/hazelcast/util/Preconditions.h
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/src/hazelcast/client/proxy.cpp
  hazelcast/test/src/HazelcastTests2.cpp
  hazelcast/test/src/HazelcastTests3.cpp
Labels: Type: Defect

#861 Update the client version to 4.1.0 for the new release
  CMakeLists.txt
  Reference_Manual.md
  examples/CMakeLists.txt
Labels: Type: Documentation, Type: Enhancement

#862 Clarified the documentation and api reference links
  README.md
Labels: Type: Documentation
