Repository hazelcast/hazelcast-cpp-client, pull requests merged in 2021-03, with the labels that each got.

#808 Cleanup CMake files for tests
  CMakeLists.txt
  cmake/Modules/FindThrift.cmake
  examples/CMakeLists.txt
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/test/CMakeLists.txt
  hazelcast/test/src/CMakeLists.txt
  hazelcast/test/src/ClientTestSupportBase.h
  hazelcast/test/src/HazelcastTests1.cpp
  hazelcast/test/src/HazelcastTests2.cpp
  hazelcast/test/src/HazelcastTests3.cpp
  hazelcast/test/src/HazelcastTests5.cpp
  hazelcast/test/src/HazelcastTests7.cpp
  hazelcast/test/src/HazelcastTests8.cpp
  hazelcast/test/src/cp_test.cpp
  hazelcast/test/src/logger_test.cpp
  scripts/test-unix.sh
Labels: Type: Defect, Type: Enhancement

#820 Mutual authentication Implementation
  examples/tls/BasicTLSClient.cpp
  hazelcast/include/hazelcast/client/config/ssl_config.h
  hazelcast/include/hazelcast/client/internal/socket/SocketFactory.h
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/test/resources/client1-cert.pem
  hazelcast/test/resources/client1-key.pem
  hazelcast/test/resources/client2-cert.pem
  hazelcast/test/resources/client2-key.pem
  hazelcast/test/resources/hazelcast-default-ca.xml
  hazelcast/test/resources/hazelcast-ma-optional.xml
  hazelcast/test/resources/hazelcast-ma-required.xml
  hazelcast/test/resources/hazelcast-ssl-server1.xml
  hazelcast/test/resources/server1-cert.pem
  hazelcast/test/resources/server2-cert.pem
  hazelcast/test/src/HazelcastTests1.cpp
  scripts/start-rc.bat
  scripts/start-rc.sh
Labels: Type: Enhancement

#821 Added `Vcpkg Users` section for how to use the library with the Vcpkg
  README.md
  Reference_Manual.md
Labels: Type: Documentation

#819 API-125 Add Github Actions workflows for nightly macOS and Linux builds
  .github/workflows/nightly-macos-x86_64.yml
  .github/workflows/nightly-ubuntu-i386.yml
  .github/workflows/nightly-ubuntu-x86_64.yml
  CMakeLists.txt
  scripts/build-unix.sh
  scripts/install-boost.sh
  scripts/install-thrift.sh
  scripts/start-rc.sh
  scripts/test-unix.sh
  scripts/verify-installation-unix.sh
Labels: Type: Enhancement

#830 Fix compiler warning
  hazelcast/test/src/HazelcastTests1.cpp
Labels: Type: Enhancement

#832 [API-78] Implement the Hazelcast Cloud Discovery
  Reference_Manual.md
  examples/CMakeLists.txt
  examples/aws/AwsClientWithKey.cpp
  examples/cloud-discovery/CMakeLists.txt
  examples/cloud-discovery/connect-cloud.cpp
  examples/cloud-discovery/ssl-connect-cloud.cpp
  hazelcast/include/hazelcast/client/address.h
  hazelcast/include/hazelcast/client/aws/aws_client.h
  hazelcast/include/hazelcast/client/aws/impl/AwsAddressTranslator.h
  hazelcast/include/hazelcast/client/aws/impl/DescribeInstances.h
  hazelcast/include/hazelcast/client/config/client_network_config.h
  hazelcast/include/hazelcast/client/config/cloud_config.h
  hazelcast/include/hazelcast/client/connection/AddressProvider.h
  hazelcast/include/hazelcast/client/connection/AddressTranslator.h
  hazelcast/include/hazelcast/client/connection/ClientConnectionManagerImpl.h
  hazelcast/include/hazelcast/client/connection/Connection.h
  hazelcast/include/hazelcast/client/impl/hazelcast_client_instance_impl.h
  hazelcast/include/hazelcast/client/spi/impl/DefaultAddressProvider.h
  hazelcast/include/hazelcast/client/spi/impl/discovery/cloud_discovery.h
  hazelcast/include/hazelcast/client/spi/impl/discovery/remote_address_provider.h
  hazelcast/include/hazelcast/util/AddressHelper.h
  hazelcast/include/hazelcast/util/SyncHttpsClient.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/src/hazelcast/client/discovery.cpp
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/src/hazelcast/util/util.cpp
  hazelcast/test/src/HazelcastTests1.cpp
  hazelcast/test/src/HazelcastTests2.cpp
  hazelcast/test/src/HazelcastTests3.cpp
  hazelcast/test/src/HazelcastTests5.cpp
  hazelcast/test/src/HazelcastTests7.cpp
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Enhancement

#833 Fix testListenerSubscriptionOnSingleServerRestart
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Test-Failure

#837 Fix ClientStatisticsTests
  hazelcast/test/src/ClientTestSupport.h
  hazelcast/test/src/HazelcastTests1.cpp
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Test-Failure

#836 New client property to use a different cloud discovery query endoint
  hazelcast/include/hazelcast/client/client_properties.h
  hazelcast/include/hazelcast/client/spi/impl/discovery/cloud_discovery.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/test/src/HazelcastTests7.cpp
Labels: Type: Enhancement

#839 Docker build test fails due to resource unavailable - ClientReplicatedMapTest.testNearCacheInvalidation
  hazelcast/test/src/HazelcastTests3.cpp
Labels: Type: Test-Failure
