Repository hazelcast/hazelcast-cpp-client, pull requests merged in 2021-06, with the labels that each got.

#887 Fix monitoring clients link
  Reference_Manual.md
Labels: Type: Documentation

#891 Check connection write time for heartbeat timeouts to send new ping request [API-559, API-567]
  hazelcast/include/hazelcast/client/connection/Connection.h
  hazelcast/include/hazelcast/client/connection/ReadHandler.h
  hazelcast/include/hazelcast/client/internal/socket/BaseSocket.h
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/test/resources/short-heartbeat.xml
  hazelcast/test/src/HazelcastTests1.cpp
Labels: Type: Defect

#890 Add the constructor to `in_predicate` where we can also accept a vector [API-551]
  hazelcast/include/hazelcast/client/query/predicates.h
  hazelcast/test/src/HazelcastTests5.cpp
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Enhancement
