Repository hazelcast/hazelcast-cpp-client, pull requests merged in 2021-01, with the labels that each got.

#747 Remove `include(Find<package>)`s from CMakeLists.txt files
  CMakeLists.txt
  hazelcast/test/CMakeLists.txt
Labels: Type: Defect, Type: Enhancement

#746 Remove file name and line number in log line and the logger function API
  examples/learning-basics/configure-logging/custom_log_handler.cpp
  examples/learning-basics/destroying-instances/main.cpp
  hazelcast/include/hazelcast/logger.h
  hazelcast/src/hazelcast/logger.cpp
  hazelcast/test/src/HazelcastTests2.cpp
  hazelcast/test/src/logger_test.cpp
Labels: Type: Enhancement

#748 Fix code coverage
  scripts/do-all-unix.sh
Labels: Type: Defect

#749 Removed unused codec methods
  hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.cpp
  hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.h
  hazelcast/include/hazelcast/client/iqueue.h
  hazelcast/include/hazelcast/client/proxy/IQueueImpl.h
  hazelcast/src/hazelcast/client/proxy.cpp
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Enhancement

#750 Make `hazelcast_client::shutdown` async
  CMakeLists.txt
  README.md
  examples/Org.Website.Samples/EntryProcessorSample.cpp
  examples/Org.Website.Samples/ExecutorSample.cpp
  examples/Org.Website.Samples/IdentifiedDataSerializableSample.cpp
  examples/Org.Website.Samples/ListSample.cpp
  examples/Org.Website.Samples/MapSample.cpp
  examples/Org.Website.Samples/MultiMapSample.cpp
  examples/Org.Website.Samples/PortableSerializableSample.cpp
  examples/Org.Website.Samples/QuerySample.cpp
  examples/Org.Website.Samples/QueueSample.cpp
  examples/Org.Website.Samples/ReplicatedMapSample.cpp
  examples/Org.Website.Samples/RingBufferSample.cpp
  examples/Org.Website.Samples/SetSample.cpp
  examples/Org.Website.Samples/TopicSample.cpp
  examples/event-properties/SetEventThreadCountAndMaxQueueSize.cpp
  examples/network-configuration/connection-strategy/DoNotReconnectToCluster.cpp
  examples/network-configuration/connection-strategy/ReconnectAsync.cpp
  examples/network-configuration/connection-strategy/StartAsync.cpp
  examples/network-configuration/connection-strategy/cluster_connection_retry.cpp
  hazelcast/include/hazelcast/client/hazelcast_client.h
  hazelcast/include/hazelcast/client/protocol/ClientMessage.h
  hazelcast/include/hazelcast/client/serialization/pimpl/data_input.h
  hazelcast/include/hazelcast/client/serialization/pimpl/data_output.h
  hazelcast/include/hazelcast/client/serialization_config.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/protocol.cpp
  hazelcast/src/hazelcast/client/serialization.cpp
  hazelcast/test/src/HazelcastTests1.cpp
  hazelcast/test/src/HazelcastTests2.cpp
  hazelcast/test/src/HazelcastTests3.cpp
  hazelcast/test/src/HazelcastTests8.cpp
  hazelcast/test/src/cp_test.cpp
Labels: Type: Enhancement, api-change

#751 Revert the thread_pool destruction on shutdown, revert back the fix for issue https://github.com/chriskohlhoff/asio/issues/431
  hazelcast/include/hazelcast/client/spi/impl/ClientInvocation.h
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/src/hazelcast/util/util.cpp
Labels: Type: Defect

#755 Change `boost::launch::deferred` continuations to `boost::launch::async`
  hazelcast/include/hazelcast/client/connection/ClientConnectionManagerImpl.h
  hazelcast/include/hazelcast/client/hazelcast_client.h
  hazelcast/include/hazelcast/client/imap.h
  hazelcast/include/hazelcast/client/iqueue.h
  hazelcast/include/hazelcast/client/map/NearCachedClientMapProxy.h
  hazelcast/include/hazelcast/client/proxy/ReplicatedMapImpl.h
  hazelcast/include/hazelcast/client/proxy/SerializingProxy.h
  hazelcast/include/hazelcast/client/spi/ProxyManager.h
  hazelcast/include/hazelcast/client/spi/impl/ClientInvocation.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/src/hazelcast/client/proxy.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/src/hazelcast/client/transactions.cpp
  hazelcast/src/hazelcast/cp/cp.cpp
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Defect

#756 Remove the `iexecutor_service` methods using the callbacks, remove user executor, remove ResponseProcessor
  README.md
  examples/Org.Website.Samples/ExecutorSample.cpp
  hazelcast/include/hazelcast/client/client_properties.h
  hazelcast/include/hazelcast/client/connection/ClientConnectionManagerImpl.h
  hazelcast/include/hazelcast/client/iexecutor_service.h
  hazelcast/include/hazelcast/client/multi_execution_callback.h
  hazelcast/include/hazelcast/client/spi/impl/ClientExecutionServiceImpl.h
  hazelcast/include/hazelcast/client/spi/impl/ClientInvocationServiceImpl.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/test/src/HazelcastTests7.cpp
Labels: Type: Cleanup, Type: Enhancement

#759 Fix boost version in cmake pkg config and fix multi config check
  CMakeLists.txt
  cmake/config.cmake.in
Labels: Type: Defect

#758 Update README sections for installing and linking
  README.md
Labels: Type: Documentation

#762 Increase the default value for cluster connection timeout
  hazelcast/include/hazelcast/client/config/connection_retry_config.h
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Enhancement

#765 Replaced `boost::launch::async` continuation with thread pool based continuation
  hazelcast/include/hazelcast/client/internal/socket/BaseSocket.h
  hazelcast/include/hazelcast/client/spi/ProxyManager.h
  hazelcast/include/hazelcast/client/spi/impl/ClientExecutionServiceImpl.h
  hazelcast/include/hazelcast/client/spi/impl/ClientInvocation.h
  hazelcast/include/hazelcast/client/spi/impl/ClientInvocationServiceImpl.h
  hazelcast/include/hazelcast/util/hz_thread_pool.h
  hazelcast/src/hazelcast/client/proxy.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/src/hazelcast/cp/cp.cpp
  hazelcast/src/hazelcast/logger.cpp
  hazelcast/src/hazelcast/util/util.cpp
  hazelcast/test/src/HazelcastTests1.cpp
Labels: Type: Defect

#766 Replace the word UTF with string
  hazelcast/include/hazelcast/client/serialization/pimpl/data_input.h
  hazelcast/include/hazelcast/client/serialization/serialization.h
  hazelcast/test/src/HazelcastTests1.cpp
Labels: Type: Enhancement

#767 Changed the default cluster connection timeout to infinite
  hazelcast/include/hazelcast/client/config/connection_retry_config.h
Labels: Type: Enhancement

#763 Minor fixes README and examples
  README.md
  examples/serialization/custom/main.cpp
  examples/serialization/globalserializer/main.cpp
  examples/serialization/identified-data-serializable/main.cpp
  examples/serialization/portable/main.cpp
Labels: Type: Documentation, Type: Enhancement

#805 Fix ToC links
  README.md
Labels: Type: Documentation
