Repository hazelcast/hazelcast-cpp-client, pull requests merged in 2021-08, with the labels that each got.

#893 Fix the msecs part printing of the time strings in the logs [API-560]
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/src/hazelcast/util/util.cpp
  hazelcast/test/src/HazelcastTests2.cpp
Labels: Type: Defect

#905 Fix dockerfiles
  docker/hazelcast-fedora-i386.dockerfile
  docker/hazelcast-fedora-x86_64.dockerfile
Labels: Type: Defect

#912 Add .i686 suffix to openssl package in 32 bit dockerfile
  docker/hazelcast-fedora-i386.dockerfile
Labels: Type: Defect

#909 [API-597] Implementation external public address usage support
  Reference_Manual.md
  examples/CMakeLists.txt
  examples/external-smart-client-discovery/CMakeLists.txt
  examples/external-smart-client-discovery/README.md
  examples/external-smart-client-discovery/connect-external-client.cpp
  hazelcast/include/hazelcast/client/config/client_network_config.h
  hazelcast/include/hazelcast/client/connection/AddressProvider.h
  hazelcast/include/hazelcast/client/connection/ClientConnectionManagerImpl.h
  hazelcast/include/hazelcast/client/member.h
  hazelcast/include/hazelcast/client/protocol/ClientMessage.h
  hazelcast/include/hazelcast/client/spi/impl/ClientClusterServiceImpl.h
  hazelcast/include/hazelcast/client/spi/impl/DefaultAddressProvider.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/cluster.cpp
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Enhancement

#913 Fix dangling string reference
  hazelcast/include/hazelcast/client/impl/EntryEventHandler.h
  hazelcast/include/hazelcast/client/impl/ItemEventHandler.h
Labels: Type: Defect

#916 Do not re-schedule backup event timer if connection is closing and client is shutting down
  hazelcast/src/hazelcast/client/network.cpp
Labels: Type: Defect

#917 Change the client release version from 4.1.1 to 4.2.0
  CMakeLists.txt
  Reference_Manual.md
  examples/CMakeLists.txt
Labels: Type: Enhancement

#919 Clarify the documentation about client config options
  Reference_Manual.md
Labels: Type: Enhancement, Type: Documentation

#921 Change use of std::atomic<time_point> with std::atomic<duration>
  hazelcast/include/hazelcast/client/connection/Connection.h
  hazelcast/include/hazelcast/client/connection/ReadHandler.h
  hazelcast/include/hazelcast/client/internal/socket/BaseSocket.h
  hazelcast/src/hazelcast/client/network.cpp
Labels: Type: Defect

#920 [API-603] Update hazelcast.org links
  README.md
  Reference_Manual.md
  examples/README.md
  examples/client-statistics/hazelcast-management-center-enabled.xml
Labels: Type: Documentation

#922 Revert boost version to 1.72 for fedora 22 docker
  docker/hazelcast-fedora22-x86_64.dockerfile
Labels: Type: Enhancement
