Repository hazelcast/hazelcast-cpp-client, pull requests merged in 2022-12, with the labels that each got.

#1041 MSVC linker error fix.(#1040)
  hazelcast/include/hazelcast/client/member.h
Labels: compilation-error

#1038 Links are made absolute.
  README.md
Labels: Type: Documentation

#1047 Fix runner-image version for coverage.yml
  .github/workflows/coverage-report.yaml
Labels: compilation-error

#1043 Deprecated std::random_shuffle usage replaced.
  hazelcast/include/hazelcast/client/connection/ClientConnectionManagerImpl.h
Labels: compilation-error

#1035 SQL Module documentation has added to Reference_Manual.md. [API-1635]
  Reference_Manual.md
Labels: Type: Documentation

#1048 Cyclic dependency shared block
  hazelcast/include/hazelcast/client/sql/sql_page.h
  hazelcast/src/hazelcast/client/sql.cpp
  hazelcast/test/src/sql_test.cpp
Labels: Type: Defect, Type: Critical

#1044 Discovery token is filtered out in exception message [API-1738].
  hazelcast/include/hazelcast/util/SyncHttpsClient.h
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/src/hazelcast/util/util.cpp
  hazelcast/test/src/HazelcastTests7.cpp
Labels: Type: Defect

#1058 sql_advanced_query_options example is added.
  examples/sql/CMakeLists.txt
  examples/sql/sql_advanced_query_options.cpp
Labels: Type: Enhancement

#1057 5.0.0 references replaced with 5.1.0
  Reference_Manual.md
Labels: Type: Documentation

#1059 Api 1794
  hazelcast/test/resources/hazelcast-sql-without-jet.xml
  hazelcast/test/resources/lock-expiration.xml
  hazelcast/test/src/HazelcastTests8.cpp
  hazelcast/test/src/TestHelperFunctions.h
  hazelcast/test/src/cp_test.cpp
  hazelcast/test/src/remote_controller_client.cpp
  hazelcast/test/src/remote_controller_client.h
  hazelcast/test/src/sql_test.cpp
  scripts/start-rc.sh
Labels: Type: Test-Failure

#1061 Refactor for gcc 4-8-5.
  hazelcast/include/hazelcast/client/sql/sql_service.h
  hazelcast/src/hazelcast/client/sql.cpp
  hazelcast/test/src/HazelcastTests7.cpp
Labels: compilation-error

#1046 Fix for const qualified warnings
  hazelcast/include/hazelcast/client/client_config.h
  hazelcast/include/hazelcast/client/internal/nearcache/NearCache.h
  hazelcast/include/hazelcast/client/internal/nearcache/impl/DefaultNearCache.h
  hazelcast/include/hazelcast/client/map/impl/nearcache/InvalidationAwareWrapper.h
  hazelcast/include/hazelcast/client/proxy/flake_id_generator_impl.h
  hazelcast/include/hazelcast/client/serialization/serialization.h
  hazelcast/include/hazelcast/util/SynchronizedMap.h
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/src/hazelcast/client/proxy.cpp
  hazelcast/src/hazelcast/client/serialization.cpp
Labels: Source: Community

#1063 Reference type is changed to pointer.
  hazelcast/include/hazelcast/client/sql/sql_result.h
  hazelcast/src/hazelcast/client/sql.cpp
Labels: compilation-error

#1064 Fix pessimistic-move warning.
  hazelcast/test/src/sql_test.cpp
Labels: compilation-error

#1073 Crash problem is fixed when an adress is not found in private_to_public map.
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Defect

#1074 Crash problem is fixed when an adress could not be translated by address provider. (#1073)
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Defect
