Repository hazelcast/hazelcast-cpp-client, pull requests merged in 2023-03, with the labels that each got.

#1067 Schema distribution on cluster-restart is implemented [API-1328]
  hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.cpp
  hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.h
  hazelcast/include/hazelcast/client/connection/ClientConnectionManagerImpl.h
  hazelcast/include/hazelcast/client/exception/protocol_exceptions.h
  hazelcast/include/hazelcast/client/impl/hazelcast_client_instance_impl.h
  hazelcast/include/hazelcast/client/protocol/ClientMessage.h
  hazelcast/include/hazelcast/client/serialization/pimpl/compact/default_schema_service.h
  hazelcast/include/hazelcast/client/spi/impl/ClientInvocationServiceImpl.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/compact.cpp
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/src/hazelcast/client/protocol.cpp
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/test/src/ClientTest.cpp
  hazelcast/test/src/TestHelperFunctions.h
  hazelcast/test/src/compact/compact_schema_replication_on_cluster_restart_test.h
  hazelcast/test/src/compact_test.cpp
Labels: Type: Enhancement, Estimation: M

#1080 ODR violation because of defaulting parameter of template function by lambda declaration.
  hazelcast/include/hazelcast/client/protocol/ClientMessage.h
Labels: compilation-error

#1128 Unused `this` capture is removed.
  hazelcast/src/hazelcast/client/network.cpp
Labels: compilation-error

#1053 Forward declaration was done starting from hazelcast_client.h
  hazelcast/include/hazelcast/client/hazelcast_client.h
  hazelcast/include/hazelcast/client/impl/hazelcast_client_instance_impl.h
  hazelcast/include/hazelcast/client/iqueue.h
  hazelcast/include/hazelcast/client/proxy/PNCounterImpl.h
  hazelcast/include/hazelcast/client/proxy/PartitionSpecificClientProxy.h
  hazelcast/include/hazelcast/client/proxy/ReplicatedMapImpl.h
  hazelcast/include/hazelcast/client/proxy/RingbufferImpl.h
  hazelcast/include/hazelcast/client/replicated_map.h
  hazelcast/include/hazelcast/client/ringbuffer.h
  hazelcast/include/hazelcast/client/ringbuffer/read_result_set.h
  hazelcast/include/hazelcast/client/serialization/pimpl/data.h
  hazelcast/include/hazelcast/client/spi/impl/ClientPartitionServiceImpl.h
  hazelcast/include/hazelcast/client/transaction_context.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/src/hazelcast/client/proxy.cpp
  hazelcast/src/hazelcast/client/spi.cpp
Labels: Type: Enhancement, Source: Community

#1127 local_date parse bug is fixed. Tests are added.
  hazelcast/include/hazelcast/client/protocol/ClientMessage.h
  hazelcast/test/src/ClientTest.h
  hazelcast/test/src/sql_test.cpp
Labels: Type: Defect

#1131 context is not protected, then is made sync
  hazelcast/src/hazelcast/client/spi.cpp
Labels: Type: Test-Failure

#1132 Listener unhandled exception
  hazelcast/src/hazelcast/client/spi.cpp
Labels: Type: Test-Failure

#1139 Log output is fixed.
  hazelcast/src/hazelcast/client/network.cpp
Labels: Type: Defect, Estimation: S

#1140 [API-1328] Cluster reconnect coverage increased.
  hazelcast/include/hazelcast/client/connection/ClientConnectionManagerImpl.h
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/test/src/HazelcastTests8.cpp
  hazelcast/test/src/compact/compact_test_base.h
Labels: Type: Cleanup, Estimation: S, Source: Internal

#1082 Compact fetch schema on read is implemented. [Api 1327]
  hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.cpp
  hazelcast/generated-sources/src/hazelcast/client/protocol/codec/codecs.h
  hazelcast/include/hazelcast/client/protocol/ClientMessage.h
  hazelcast/include/hazelcast/client/serialization/field_kind.h
  hazelcast/include/hazelcast/client/serialization/pimpl/compact/compact.h
  hazelcast/include/hazelcast/client/serialization/pimpl/compact/compact_impl.h
  hazelcast/include/hazelcast/client/serialization/pimpl/compact/default_schema_service.h
  hazelcast/include/hazelcast/client/serialization/pimpl/compact/schema.h
  hazelcast/src/hazelcast/client/compact.cpp
  hazelcast/src/hazelcast/client/network.cpp
  hazelcast/test/resources/compact.xml
  hazelcast/test/src/compact/compact_field_kind_test.h
  hazelcast/test/src/compact/compact_helper.h
  hazelcast/test/src/compact/compact_nullable_primitive_interoperability_test.h
  hazelcast/test/src/compact/compact_read_write_integration_test.h
  hazelcast/test/src/compact/compact_schema_fetch_on_read.h
  hazelcast/test/src/compact/compact_schema_replication_on_cluster_restart_test.h
  hazelcast/test/src/compact/compact_schema_replication_on_write_test.h
  hazelcast/test/src/compact/compact_schema_replication_stress_test.h
  hazelcast/test/src/compact/compact_schema_test.h
  hazelcast/test/src/compact/compact_schema_validation_test.h
  hazelcast/test/src/compact/compact_serialization_test.h
  hazelcast/test/src/compact/compact_test_base.h
  hazelcast/test/src/compact/serialization/bits_dto.h
  hazelcast/test/src/compact/serialization/employee_dto.h
  hazelcast/test/src/compact/serialization/empty_main_dto.h
  hazelcast/test/src/compact/serialization/inner_dto.h
  hazelcast/test/src/compact/serialization/main_dto.h
  hazelcast/test/src/compact/serialization/named_dto.h
  hazelcast/test/src/compact/serialization/nested_type.h
  hazelcast/test/src/compact/serialization/node_dto.h
  hazelcast/test/src/compact/serialization/nullable_primitive_object.h
  hazelcast/test/src/compact/serialization/primitive_object.h
  hazelcast/test/src/compact/serialization/sample_compact_type.h
  hazelcast/test/src/compact/serialization/stress_type.h
  hazelcast/test/src/compact_test.cpp
Labels: Estimation: M

#1134 Fix pedantic warnings for cleaning up
  hazelcast/include/hazelcast/client/internal/nearcache/NearCacheManager.h
  hazelcast/include/hazelcast/client/membership_listener.h
  hazelcast/include/hazelcast/client/proxy/RingbufferImpl.h
  hazelcast/include/hazelcast/client/serialization/pimpl/data.h
  hazelcast/include/hazelcast/client/serialization/serialization.h
Labels: Type: Enhancement, Estimation: S, Source: Community

#1135 Include iosfwd instead of xstream system header file
  hazelcast/include/hazelcast/client/address.h
  hazelcast/include/hazelcast/client/config/client_aws_config.h
  hazelcast/include/hazelcast/client/config/eviction_config.h
  hazelcast/include/hazelcast/client/connection/Connection.h
  hazelcast/include/hazelcast/client/entry_event.h
  hazelcast/include/hazelcast/client/exception/iexception.h
  hazelcast/include/hazelcast/client/hazelcast_json_value.h
  hazelcast/include/hazelcast/client/map_event.h
  hazelcast/include/hazelcast/client/member.h
  hazelcast/include/hazelcast/client/member_selectors.h
  hazelcast/include/hazelcast/client/protocol/ClientMessage.h
  hazelcast/include/hazelcast/client/protocol/Principal.h
  hazelcast/include/hazelcast/client/serialization/field_kind.h
  hazelcast/include/hazelcast/client/serialization/pimpl/compact/schema.h
  hazelcast/include/hazelcast/client/serialization/pimpl/data_input.h
  hazelcast/include/hazelcast/client/spi/impl/ClientInvocation.h
  hazelcast/include/hazelcast/client/sql/impl/query_id.h
  hazelcast/include/hazelcast/util/AddressHelper.h
  hazelcast/include/hazelcast/util/Sync.h
  hazelcast/include/hazelcast/util/SynchronizedMap.h
  hazelcast/include/hazelcast/util/SynchronizedQueue.h
Labels: Type: Enhancement, Estimation: S, Source: Community

#1142 Ambiguity fixed. [API-1511]
  Reference_Manual.md
Labels: Type: Documentation, Estimation: S, Source: Internal

#1136 Forgetten int8_t type support for vector data output
  hazelcast/include/hazelcast/client/serialization/pimpl/data_output.h
  hazelcast/test/src/HazelcastTests1.cpp
Labels: Type: Defect, Estimation: S

#1150 get_field_kind is added.
  hazelcast/include/hazelcast/client/serialization/pimpl/compact/compact.h
  hazelcast/src/hazelcast/client/compact.cpp
  hazelcast/src/hazelcast/client/compact.cpp'
  hazelcast/test/src/compact/compact_serialization_test.h
  hazelcast/test/src/compact/serialization/employee_dto.h
Labels: Estimation: S, Source: Internal

#1151 Fixes for gcc 485
  hazelcast/src/hazelcast/client/compact.cpp
  hazelcast/test/src/compact/compact_rabin_fingerprint_test.h
  hazelcast/test/src/compact/compact_schema_replication_on_cluster_restart_test.h
Labels: Priority: High, Estimation: S, Source: Internal, compilation-error

#1155 Compatibility tests are fixed.
  hazelcast/test/src/compact/compact_generic_record_builder_test.h
  hazelcast/test/src/compact/compact_generic_record_integration_test.h
  hazelcast/test/src/compact/compact_generic_record_test.h
  hazelcast/test/src/compact/compact_nullable_primitive_interoperability_test.h
  hazelcast/test/src/compact/compact_read_write_integration_test.h
  hazelcast/test/src/compact/compact_schema_fetch_on_read.h
  hazelcast/test/src/compact/compact_schema_replication_on_cluster_restart_test.h
  hazelcast/test/src/compact/compact_schema_replication_on_write_test.h
  hazelcast/test/src/compact/compact_schema_replication_stress_test.h
  hazelcast/test/src/compact/compact_schema_validation_test.h
  hazelcast/test/src/compact/compact_serialization_test.h
  hazelcast/test/src/compact/compact_test_base.h
  hazelcast/test/src/sql_test.cpp
Labels: Type: Test-Failure, Estimation: S, Source: Internal

#1141 Compact documentation is added. [API-1937]
  Reference_Manual.md
Labels: Estimation: S

#1154 version is updated to 5.2.0
  CMakeLists.txt
  Reference_Manual.md
  examples/CMakeLists.txt
Labels: Type: Documentation, Estimation: S

#1159 [BACKPORT] Do not interleave async_write calls (#988)
  hazelcast/include/hazelcast/client/internal/socket/BaseSocket.h
  hazelcast/include/hazelcast/client/protocol/ClientMessage.h
  hazelcast/test/src/HazelcastTests8.cpp
  scripts/start-rc.bat
  scripts/start-rc.sh
Labels: Type: Defect, Backport

#1165 Windows boost dependency upgrade is added to Reference_Manual.md
  Reference_Manual.md
Labels: Type: Documentation, Estimation: S, Source: Internal

#1051 page_iterator_sync is added. [API-1761]
  Reference_Manual.md
  examples/sql/CMakeLists.txt
  examples/sql/sql_page_iterator_sync.cpp
  hazelcast/include/hazelcast/client/sql/sql_result.h
  hazelcast/src/hazelcast/client/sql.cpp
  hazelcast/test/src/sql_test.cpp
Labels: Estimation: M, Source: Internal

#1172 Windows GitHub cache [API-1890]
  .github/workflows/nightly-windows.yml
Labels: Type: Enhancement, Source: Internal

#1178 sql_test comptibility test failure fix.
  hazelcast/test/src/remote_controller_client.cpp
  hazelcast/test/src/sql_test.cpp
Labels: Type: Test-Failure, Estimation: S, Source: Internal

#1182 Download hazelcast-enterprise-5.3.0-SNAPSHOT-tests.jar as well.
  .github/workflows/build-pr.yml
Labels: Estimation: S, Source: Internal

#1161 row_iterator_sync have been implemented. [API-1762]
  Reference_Manual.md
  examples/sql/CMakeLists.txt
  examples/sql/sql_row_iterator_sync.cpp
  hazelcast/include/hazelcast/client/sql/sql_result.h
  hazelcast/src/hazelcast/client/sql.cpp
  hazelcast/test/src/sql_test.cpp
Labels: Estimation: M

#1167 Sql partition aware routing[API-1862]
  hazelcast/include/hazelcast/client/client_properties.h
  hazelcast/include/hazelcast/client/sql/impl/read_optimized_lru_cache.h
  hazelcast/include/hazelcast/client/sql/sql_service.h
  hazelcast/include/hazelcast/client/sql/sql_statement.h
  hazelcast/include/hazelcast/util/SynchronizedMap.h
  hazelcast/src/hazelcast/client/client_impl.cpp
  hazelcast/src/hazelcast/client/sql.cpp
  hazelcast/test/src/sql_test.cpp
  scripts/start-rc.bat
  scripts/start-rc.sh
Labels: Type: Enhancement, Estimation: M, Source: Internal

#1187 5.3.0 update for github actions
  .github/workflows/build-pr.yml
  .github/workflows/coverage-report.yaml
  .github/workflows/nightly-macos-x86_64.yml
  .github/workflows/nightly-ubuntu-i386.yml
  .github/workflows/nightly-ubuntu-x86_64.yml
  .github/workflows/nightly-windows.yml
Labels: Type: Enhancement
