Repository hazelcast/hazelcast-cpp-client, pull requests merged in 2023-12, with the labels that each got.

#1216 Do not use the deprecated `repoUrl` mvn option when downloading the test jars [API-2183]
  scripts/start-rc.bat
  scripts/start-rc.sh
Labels: Type: Test-Failure

#1215 [NEW FEATURE] Add `on_cancel` callback handler for the reliable_listener [API-2183]
  examples/distributed-topic/reliabletopic/Publisher.cpp
  examples/distributed-topic/reliabletopic/Subscriber.cpp
  hazelcast/include/hazelcast/client/reliable_topic.h
  hazelcast/include/hazelcast/client/topic/reliable_listener.h
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Enhancement

#1217 Update the documentation for the reliable_topic listener callback on_cancel [API-2183]
  Reference_Manual.md
Labels: Type: Enhancement, Type: Documentation

#1205 Update Hazelcast documentation link version
  Reference_Manual.md
Labels: Automation: PR auto closed
