Repository hazelcast/hazelcast-cpp-client, pull requests merged in 2023-02, with the labels that each got.

#1033 rabin_finger_print unit tests are added. Some schema_tests added. [API-1297]
  hazelcast/include/hazelcast/client/serialization/pimpl/compact.h
  hazelcast/src/hazelcast/client/compact.cpp
  hazelcast/test/src/compact_test.cpp
Labels: Type: Enhancement

#1087 [API-1809]: Executor Lifecycle is extended for reliable_topic async continuation
  hazelcast/include/hazelcast/client/reliable_topic.h
  hazelcast/src/hazelcast/client/proxy.cpp
Labels: Type: Defect, Type: Test-Failure, Estimation: S

#1088 compiler error in mac os
  hazelcast/test/src/compact_test.cpp
Labels: compilation-error

#1089 Executor pool size
  hazelcast/include/hazelcast/client/spi/impl/ClientExecutionServiceImpl.h
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Enhancement, Estimation: S

#1095 Compact test failures
  hazelcast/src/hazelcast/client/compact.cpp
Labels: Type: Test-Failure

#1101 --recurse options is added for vcpkg installation.
  Reference_Manual.md
Labels: Type: Documentation

#1098 Ssl version 3 [API-1872]
  hazelcast/src/hazelcast/client/discovery.cpp
  hazelcast/test/src/HazelcastTests7.cpp
Labels: compilation-error

#1102 discovery_config_mismatches_test failures [API-1875]
  hazelcast/src/hazelcast/client/client_impl.cpp
Labels: Type: Test-Failure, Source: Internal

#1105 [API-1886] Download hazelcast-enterprise-tests.jar step has been added.
  .github/workflows/coverage-report.yaml
  .github/workflows/nightly-macos-x86_64.yml
  .github/workflows/nightly-ubuntu-i386.yml
  .github/workflows/nightly-ubuntu-x86_64.yml
  .github/workflows/nightly-windows.yml
Labels: Type: Test-Failure, Estimation: S

#1104 BaseSocket async_write buffer lifecycle [API-1814] [API-1808]
  hazelcast/include/hazelcast/client/internal/socket/BaseSocket.h
Labels: Type: Defect, Type: Test-Failure, Type: Critical, Source: Internal

#1103 ClientQueueTest.testRemainingCapacity is fixed. [API-1810]
  hazelcast/test/src/HazelcastTests7.cpp
Labels: Type: Test-Failure

#1107 Execute on closed member
  hazelcast/test/src/sql_test.cpp
Labels: Type: Test-Failure

#1109 basic_latch_test.test_wait_for_when_timeout is fixed. [API-1889]
  hazelcast/test/src/cp_test.cpp
Labels: Type: Test-Failure

#1110 Ssl ubuntu fix
  hazelcast/src/hazelcast/client/discovery.cpp
Labels: Type: Test-Failure

#1106 Compact compiler error on MacOs
  hazelcast/include/hazelcast/client/serialization/pimpl/compact/compact.h
  hazelcast/src/hazelcast/client/spi.cpp
  hazelcast/test/resources/serialization.xml
  hazelcast/test/src/HazelcastTests2.cpp
  hazelcast/test/src/HazelcastTests8.cpp
  hazelcast/test/src/TestHelperFunctions.h
  hazelcast/test/src/compact/compact_rabin_fingerprint_test.h
Labels: compilation-error

#1099 New test cases [API-1812]
  hazelcast/include/hazelcast/client/config/index_config.h
  hazelcast/include/hazelcast/client/config/near_cache_config.h
  hazelcast/include/hazelcast/cp/cp.h
  hazelcast/src/hazelcast/client/config.cpp
  hazelcast/src/hazelcast/client/discovery.cpp
  hazelcast/test/src/HazelcastTests1.cpp
  hazelcast/test/src/HazelcastTests2.cpp
  hazelcast/test/src/HazelcastTests3.cpp
  hazelcast/test/src/HazelcastTests5.cpp
  hazelcast/test/src/HazelcastTests7.cpp
  hazelcast/test/src/HazelcastTests8.cpp
  hazelcast/test/src/compact/serialization/stress_type.h
  hazelcast/test/src/cp_test.cpp
  hazelcast/test/src/serialization/Serializables.cpp
  hazelcast/test/src/serialization/Serializables.h
Labels: Type: Enhancement

#1112 boost version is updated
  .github/workflows/nightly-ubuntu-x86_64.yml
Labels: compilation-error

#1113 Boost dependency upgraded to 1.73 on Windows.
  .github/workflows/nightly-windows.yml
  CMakeLists.txt
Labels: Type: Test-Failure, Estimation: S

#1116 Boost 1.73 url for nightly-windows.yml
  .github/workflows/nightly-windows.yml
Labels: Type: Test-Failure, Estimation: S

#1119 [API-1894] Core dump on crash feature has implemented for windows job.
  .github/workflows/nightly-windows.yml
Labels: Type: Enhancement

#1118 [API-1511] -DHZ_BUILD_WITH_SSL requirement is stated.
  Reference_Manual.md
Labels: Type: Documentation

#1123 `connection_manager_translate` tests are fixed.
  hazelcast/test/src/HazelcastTests8.cpp
Labels: Type: Test-Failure

#1122 1114 reliabletopic terminate test failure [AP-1893]
  hazelcast/include/hazelcast/client/reliable_topic.h
Labels: Type: Test-Failure

#1124 ReadMe is update for Nightly Build Badges
  README.md
Labels: Type: Documentation
